import { Inter } from "next/font/google";
import { AppHeader } from "@/components/app-header";
import "../styles/main.scss";

import { AuthContextProvider } from "@/context/authContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Appointments",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <AppHeader />
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
